### ISSUE TITLE
Sounds\Update and other things...

### ISSUE THREAD

**Issue by Zelost** [alandarev/wowmod#10]
How could I update a plugin to a last version? Or it's already updated? I found some files for mysql called "Update", do I need to import them? Also there is updates.inc with some versions in it, does it already installed? Or how to install it...? Also for CS:GO - there is sound issues (no sounds at all). Also active talents do not appears in the spellbook and some other problems... Can u help me? I could pay u, if u want.
P.S. Sorry for my english....

**Comment by alandarev** [comment]
> Update scripts

Mysql Updates are not required (I removed the files to not confuse people).

> Sounds in CS:GO

Its a limitation of CS:GO engine, they do not allow sounds. Though there is a work-around I saw people use in their mods, you can apply it here with some easy modifications as well. Please refer to this topic on how-to:
https://forums.alliedmods.net/showthread.php?t=193245

Shortly, you have to convert soudns into mp3, put them inside sound\music.... and then change the code in wowmod to reflect the path changes.

> Also active talents do not appears in the spellbook and some other problems... 

I am not sure what is causing it, rely on error logs in sourecemod/logs folder.

**Sorry, but the project is no longer worked on**
It works flawlessly on cs:s, but in cs:go there are several issues pending to be solved. I won't be able to help you here, as our team has moved on to other things...

You might want to contact a russian person in skype - hojjke (his nickname). He is the last guy I know who successfully installed the CS:GO wowmod with some help about half a year ago.
