### ISSUE TITLE
2 more questions (sorry ><)

### ISSUE THREAD

**Issue by Zelost** [alandarev/wowmod#11]
Sorry about another topic. Just a few questions:
1)Do u know skype login of Hojjke? (Found over 5 russian people with dat name....) Also, there is no wowmod servers in cs:go - might be it's dead now... Can't even find someone who could re-write\fix plugin for the money ><
2)Do u have some assumptions why does Active Talents\Autocast menu dosen't work? Might I can fix it myself just like u told me about the sounds...

**Comment by alandarev** [comment]
1) Hojjke is his login name, so it should be only one person with that login, right?

2) Error logs are very good at these things (when menu doesn't open, etc). Usually its translations file.

**Comment by Zelost** [comment]
Well, there is only a few errors, but that's another story... 
`L 05/08/2016 - 13:47:18: [SM] Native "SDKCall" reported: Invalid Handle 0 (error 4)`

`L 05/08/2016 - 13:47:18: [SM] Displaying call stack trace for plugin "server\wow.smx":`

`L 05/08/2016 - 13:47:18: [SM]   [0]  Line 2748, wow/hooks.inc::DeciSecondTimer()`
and
`L 05/08/2016 - 14:42:15: [SM] Native "IsPlayerAlive" reported: Invalid client index 0`

`L 05/08/2016 - 14:42:15: [SM] Displaying call stack trace for plugin "server\wow.smx":`

 Menu are opening fine. But in autocast "nospell" only... And there is just a regular spells in the spellbook, without talents one :c

**Comment by alandarev** [comment]
Talents are not in spellbook by design.
You can't put talents into spellbar.
To use talents you have to bind keys, example: bind q "talent 1" You will find the ID (1 in the example) of talent in the talent description where you choose the talents.

**Comment by Zelost** [comment]
Thanks to u! Ok, now the only autocast problem left. Should I give u files when I fix sounds and autocast?

**Comment by alandarev** [comment]
Feel free to do the pull request.

**Comment by Zelost** [comment]
Added some files in a pull. All the plugin works but 1 skill of Rogue class - deadly poisen. It has no effects or chat info. But damage is still works via ticks... Sounds fixed. Plugin could be compiled via last SM. Could u check some effects.inc for Deadly Poisen please? Mb code is broken?
